### ISSUE TITLE
Example build crashes

### ISSUE THREAD

**Issue by Swaraj-cs** [Lamelynx/GodotUniversalIntentPlugin-Android#1]
Example build crashes.. logcat showing "Call - intent()" _____________ beginning of crash. Using version 3.4.4. Added release files to plugin folder.

**Comment by Lamelynx** [comment]
I hadn't updated the release. The example project now also has the complete plugin files.

**Comment by Swaraj-cs** [comment]
Thank you so much.. Now the other options are working except the QR code.. 

Logcat 
Call - intent(com.google.zxing.client.android.SCAN)
Call - putExtra(SCAN_MODE, QR_CODE_MODE)

And crashing. 

Need to install any application? any parameters to pass or any permissions?

**Comment by Lamelynx** [comment]
I uninstalled my QR scanner and got same issue.
Probably need to add some error handling when no application exists that can respond to the intent.

**Comment by Lamelynx** [comment]
Added error handling so you will get any error if the intent fails.
