### ISSUE TITLE
Error on module QR code: Condition "err != OK" is true.

### ISSUE THREAD

**Issue by theneoxs** [Lamelynx/GodotUniversalIntentPlugin-Android#2]
Hello
Application cancel himself work on start plugin.startActivityForResult()
Return nothing, in console write Condition "err != OK" is true.
Work on Galaxy S8, gradle 7.1.1, java 16, what wrong?

**Comment by Lamelynx** [comment]
Hi
Are you running the sample project (and Godot 3.4.4)? otherwise do you have some code example pn the issue?

**Comment by theneoxs** [comment]
Oh, it so fun: for command "com.google.zxing.client.android.SCAN" working you need install other app, and i didn's reading about this before start command

I propose to supplement the description of the need to install this application

**Comment by Lamelynx** [comment]
Thanks for the feedback. I have updated the readme file.
