### ISSUE TITLE
will this working with godot4 :?

### ISSUE THREAD

**Issue by qza2468** [Lamelynx/GodotUniversalIntentPlugin-Android#4]

**Comment by Lamelynx** [comment]
This is built on Godot plugin architecture v1 and is compatible with Godit 4.1 and below. Godot 4.2 has a new plugin architecture (v2), as of this time this plugin does not support v2.

**Comment by qza2468** [comment]
Awesome, I use the godot4.1, i will try your library, Thank you!

**Comment by Lamelynx** [comment]
👍
